### ISSUE TITLE
Question on ox-odt : How to export special block as a two column section?

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode#1]
Hello,
I couldn't find my answer any where, if this is not appropriate as an issue, please feel free to close it.
What I want to do is implement a special block, say, "Sect2", in an org file

    #+attr_odt: :style Sect_2
    #+begin_sect2
    * heading 1
    ** subheading 1
    * heading 2
    #+end_sect2

"Sect_2" is a style defined in the template.

    <style:style style:name="Sect2" style:family="section">
      <style:section-properties text:dont-balance-text-columns="false" style:editable="false">
        <style:columns fo:column-count="2" fo:column-gap="0in">
          <style:column style:rel-width="4986*" fo:start-indent="0in" fo:end-indent="0in"/>
          <style:column style:rel-width="4986*" fo:start-indent="0in" fo:end-indent="0in"/>
        </style:columns>
      </style:section-properties>
    </style:style>

and the special block is translated according to the following template in the
final odt file. The name of the traslated block should increase automatically,
like "Sect_2_1", "Sect_2_2".

    <text:section text:style-name="Sect_2" text:name="Sect_2_1">
    [content]
    <text:section>

Can anyone give me some tips on how to do this?
Thank you so much!

**Comment by QiangF** [comment]
I modified org-odt-special-block as the following:

    (defun org-odt-special-block (special-block contents info)
    "Transcode a SPECIAL-BLOCK element from Org to ODT.
    CONTENTS holds the contents of the block.  INFO is a plist
    holding contextual information."
    (let ((type (org-element-property :type special-block))
    (attributes (org-export-read-attribute :attr_odt special-block)))
        (cond
        ;; Annotation.
        ;; Textbox.
        ((string= type "textbox")
            (let ((width (plist-get attributes :width))
            (height (plist-get attributes :height))
            (style (plist-get attributes :style))
            (extra (plist-get attributes :extra))
            (anchor (plist-get attributes :anchor)))
              (format "\n<text:p text:style-name=\"%s\">%s</text:p>" "Text_20_body"
                      (org-odt--textbox contents width height style extra anchor))))
        ((string= type "my-section")
            (let ((columns (plist-get attributes :columns)))
                (format "\n<text:section text:style-name=\"Sect%s\" text:name=%s>%s</text:section>"
                columns (car (org-odt-add-automatic-style "Sect")) contents )))
        (t contents))))

and created custom section styles like "Sec2" "Sec3" etc. The following works,
but the table frame size is not correct.

    #+ATTR_ODT: :columns 2
    #+BEGIN_my-section
    #+CAPTION: test
    #+label: damoaokeng
    #+ATTR_ODT: :width 6
    [[./fig.jpg]]

    #+ATTR_ODT: :rel-width 50
    |hi|lo|

    #+CAPTION: test
    #+ATTR_ODT: :width 6
    [[./fig.jpg]]

    #+ATTR_ODT: :rel-width 50
    |hi|lo|
    #+END_my-section

and the multicolumn section can't have headings. The following doesn't work.

    #+ATTR_ODT: :columns 2
    * hello
        hello
    #+END_my-section

How can I make my-section to be the greatest element of all and expands in the
last moment?

**Comment by kjambunathan** [comment]
Please talk about your _content_ of your file.  Send me a sample Org file and provide a mock PDF of the rendering that you hope to achieve.  You can create these sample mock PDFs using LibreOffice GUI or Org's LaTeX/PDF exporter or "Print PDF" of HTML file. 

For example, 

1. Do you have two src blocks which you want to compare line-by-line, by placing  them in two column format?
2. Do you have two images that you want to place side-by-side, so that you can compare and contrast among them?
3.  Or do you want to format the whole file in two or multiple formats?

Any enhancements that I provide will be on my local repository alone.

**Comment by kjambunathan** [comment]
I have basic infrastructure in place to achieve what you want.  I have started working on ODT exporter after a long gap.   In a week or two, my repository should be good for public consumption.

**Comment by QiangF** [comment]
I have attached 3 file, 
1. the org file with descriptions the functionalities I am wishing for.
 http://s000.tinyupload.com/?file_id=64277433648482888705
2. the odt file generated from the org file with modification in libreoffice.
 http://s000.tinyupload.com/?file_id=03141676724260161887
3. a odt example showing multi-object anchored in one common frame.
 http://s000.tinyupload.com/?file_id=83085547755095859652

I am new to emacs but Org odt exporter saves me a lot of time already, I hope I
can contribute someday. Thank you so much!

**Comment by QiangF** [comment]
Set style via #+attr_odt doesn't work for some element, such as

    #+ATTR_ODT: :p-style "Text_20_body_20_bold"
    #+BEGIN_CENTER
    Org mode is amazing
    #+END_CENTER

**Comment by QiangF** [comment]
Two more new glitches:
1. unable to turn page number off

    #+OPTIONS: num:nil
2. reset heading number for heading, let heading get it numbering from attr_odt,
   such as:

    #+ATTR_ODT: num:1
    * heading1

   to disable heading number, use

    #+ATTR_ODT: num:nil
    * heading1

**Comment by QiangF** [comment]
The approach using special block to implement multicolumn section fails when the
section starts on a new page, I have a file with this content, exported odt file
is here
 http://s000.tinyupload.com/?file_id=05367535323617866349
it looks terrible, libreoffice is no replacement for latex after all.

    #+OPTIONS: AUTHOR:nil toc:nil

    #+ATTR_ODT: :columns 3
    #+BEGIN_my-section
    #+CAPTION: figure 1
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 2
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 3
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]
    #+END_my-section

    #+ODT: <text:line-break/>


    #+ATTR_ODT: :columns 3
    #+BEGIN_my-section
    #+CAPTION: figure 1
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 2
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 3
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]
    #+END_my-section

    #+ODT: <text:line-break/>


    #+ATTR_ODT: :columns 3
    #+BEGIN_my-section
    #+CAPTION: figure 1
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 2
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]

    #+CAPTION: figure 3
    #+ATTR_ODT: :width 4.5 :style "OrgDisplayImage" :anchor "as-char"
    [[./fun.jpeg]]
    #+END_my-section

    #+ODT: <text:line-break/>

**Comment by QiangF** [comment]
Changing the anchor type to as-char solves the misplacement of images. See 
https://forum.openoffice.org/en/forum/viewtopic.php?f=7&t=89587&p=422278#p422278

    Image layout is often more stable/predictable if you switch the anchor mode to
    "as character". Since you have inserted captions, which adds a text frame to
    keep the image and caption together, I change the anchor mode on the frames.

Maybe as-char anchor type should be used for all cases?

**Comment by kjambunathan** [comment]
The caption above has the nuber of two parent level, how to let it only include one section level number? 

You need to customize the variable `org-odt-display-outline-level`

**Comment by kjambunathan** [comment]
This is how you style paragraphs in a centered block.

    #+BEGIN_CENTER
    Some text
    #+END_CENTER

    #+ATTR_ODT: :style "OrgFootnoteCenter"
    #+BEGIN_CENTER
    Some text
    #+END_CENTER

`OrgCenter` and `OrgFootnoteCenter` are styles defined in `etc/styles/OrgOdtStyles.xml`.  To know which style file is getting used, look for the messages like the one down below in your `*Messages*` buffer,

    Loading ox-odt...
    Debug (ox-odt): Searching for OpenDocument styles files...
    Debug (ox-odt): Trying /usr/share/emacs/etc/org/styles/... [2 times]
    Debug (ox-odt): Trying /home/kjambunathan/src/ox-odt/etc/styles/...
    Debug (ox-odt): Using styles under /home/kjambunathan/src/ox-odt/etc/styles/

**Comment by kjambunathan** [comment]
Hello,

When you mix multiple features / questions etc in a single issue, I get confused.  I suggest that you open an issue, for each question you might have.

Thanks.
