### ISSUE TITLE
org odt export: How to embed image in table

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode#2]
I have an idea, can any help me make this work?

1. make my custom figure link like: {./fig.jpg}, in an org table it looks like:

    | <l8>        | <l2> |
    | {./fig.jpg} |      |

2. before exporting the org file, replace all my custom figure link with

    @@odt:< draw:frame draw:style-name="SimpleTableFrame" 
    draw:name="Image_1"
    text:anchor-type="paragraph"
    svg:width= [width]
    style:rel-height="scale"
    svg:width= [height]
    style:rel-height="scale">
    <draw:image draw:style-name="SimpleDrawImage"
        xlink:href=[path]/>
    \</ draw:frame\>@@

[width] is the table column width, and height is the height keep aspect ratio (how to
get the height), [path] is figure path.

In the style file, create two new styles:

    <style:style style:name="SimpleTableFrame" style:family="graphic" style:parent-style-name="Graphics">
        <style:graphic-properties
        style:mirror="none"
        fo:clip="rect(0in, 0in, 0in, 0in)"
        draw:luminance="0%"
        draw:contrast="0%"
        draw:red="0%"
        draw:green="0%"
        draw:blue="0%"
        draw:gamma="100%"
        draw:color-inversion="false"
        draw:image-opacity="100%"
        draw:color-mode="standard"/>
    </style:style>

    <style:style style:name="SimpleDrawImage" style:family="graphic" style:parent-style-name="Graphics">
        <style:graphic-properties
        xlink:type="simple"
        xlink:show="embed"
        xlink:actuate="onLoad"/>
    </style:style>

**Comment by QiangF** [comment]
Seems place image in table is the best solution to achieve a side by side image layout.
http://www.linux-magazine.com/Online/Blogs/Off-the-Beat-Bruce-Byfield-s-Blog/The-mysteries-of-positioning-pictures-in-LibreOffice-OpenOffice

**Comment by kjambunathan** [comment]
You need a feature called "list-table" s.  

> #+ATTR_ODT: :style "GriddedTable"
> #+ATTR_ODT: :rel-width 50 
> #+ATTR_ODT: :list-table t
> -
>   - [[./org-mode-unicorn.png]]
>   - [[./org-mode-unicorn.png]]

When you export the above snippet, using _my github fork_, you will end up with following ODT document.
[test.docx](https://github.com/kjambunathan/org-mode/files/1161103/test.docx)

**Comment by kjambunathan** [comment]
When an image link occurs as part of flowing text, it gets embedded as a character.  You cannot attach a label or a caption to such images.  You may want to experiment with the following two snippets:

#### Snippet 1

    You see two orgmode icons here [[./org-mode-unicorn.png]]
    [[./org-mode-unicorn.png]].  They are embedded as characters.

#### Snippet 2

    #+BEGIN_CENTER
      [[./org-mode-unicorn.png]] [[./org-mode-unicorn.png]]
    #+END_CENTER

#### Snippet 3

    #+BEGIN_textbox
    [[./org-mode-unicorn.png]] [[./org-mode-unicorn.png]] 

    #+BEGIN_CENTER
    Some text
    #+END_CENTER

    #+END_textbox

#### Snippet 4

    #+ATTR_ODT: :p-style "OrgCenter"
    #+BEGIN_textbox
    [[./org-mode-unicorn.png]] [[./org-mode-unicorn.png]] 

    Some text

    #+END_textbox
